spring.application.name=auth-code-flow

spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-id=oauth2-authorization-code-flow
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.client-secret=gI1EazuxOBF9UYv9Ab1ZWhC0CppTsPEp
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.oauth2-authorization-code-flow.issuer-uri=http://127.0.0.1:8444/realms/oauth2-demos
spring.security.oauth2.client.registration.oauth2-authorization-code-flow.redirect-uri=http://localhost:9000/login/oauth2/code/oauth2-authorization-code-flow

logging.level.org.springframework.security.oauth2=DEBUG

server.port=9000